export const CALCULATOR_UPDATE = 'CALCULATOR_UPDATE';
export const BOTTLE_UPDATE = 'BOTTLE_UPDATE';
export const ADD_SMALL_BOTTLES = 'ADD_SMALL_BOTTLES';
export const REMOVE_SMALL_BOTTLES = 'REMOVE_SMALL_BOTTLES';
export const ADD_BIG_BOTTLES = 'ADD_BIG_BOTTLES'; 
export const REMOVE_BIG_BOTTLES = 'REMOVE_BIG_BOTTLES';